### ISSUE TITLE
I cannot post images to bluesky, only text

### ISSUE THREAD

**Issue by jeremygwa** [sanko/Bluesky.pm#1]
I cannot post images to bluesky, only text.

I am using strawberry perl 5.40 64bit on Windows 10

here is some example code

my $bsky = Bluesky->new();
$bsky->login( 'user', 'p.a.s.s' );
$bsky->createPost(
embed    => { image => ['D:/art/displate/Statue of Liberty July 4th Celebration Abstract Art_7730392.jpg'] }, 
    lang     => 'en',
    text     => 'this is a test',
);

**Comment by sanko** [comment]
`image` should be plural.

**Comment by jeremygwa** [comment]
Sorry that was a typo.

Even with 'image' as 'images', I cannot post images.

If I remove the 'images', I can make a text post.

________________________________

**Comment by sanko** [comment]
No error message? Are you sure the path to the image is correct? Are the forward slashes on Windows a problem?

You're not even giving me enough to base a solid theory on here.

**Comment by jeremygwa** [comment]
There is no error messages.

I believe I tried the slashes both ways

Does the path accept spaces in the file name?


________________________________

**Comment by jeremygwa** [comment]
Hi Sanko

How do I go about  posting image using raw data as the image source, rather than file path?

Do you have an example. Thanks in advance!

Regards

Jeremy

**Comment by jeremygwa** [comment]
here is a code snippet that is Not working. 
I get no Error message, but nothing gets posted.

#++++++++++++++++++++++++++++++++++++++++++++++++
sub post_status_with_media {
    my ( $status,$mediapath) = @_;
my $bsky = Bluesky->new();
$bsky->login( me@mail.com', 'xxxx-xxxx-xxxx-xxxx' );
$bsky->createPost(
embed    => { images => [rawdatafromfile('D:/art/displate/Statue of Liberty July 4th Celebration Abstract Art_7730392.jpg')] },
    lang     => 'en',
    text     => 'this is a test',
);
  
}


sub rawdatafromfile {
my ($path) = @_;
open(FH,$path);
binmode FH;
my $bin = \<FH\>;
$b64 = 'data:image/jpeg;base64,'.MIME::Base64::encode_base64($bin);
close(FH);
return $b64;
}

**Comment by jeremygwa** [comment]
my second attempt. No Errors, But still No post

#++++++++++++++++++++++++++++++++++++++++++++++++
sub post_status_with_media {
my ( $status,$mediapath) = @_;
my $bsky = Bluesky->new();
$bsky->login( me@mail.com', 'xxxx-xxxx-xxxx-xxxx' );
$bsky->createPost(
embed    => { images => [ { image=> rawdatafromfile('D:/art/displate/Statue of Liberty July 4th Celebration Abstract Art_7730392.jpg') } ] },
    lang     => 'en',
    text     => 'this is a test',
);
  
}


sub rawdatafromfile {
my ($path) = @_;
open(FH,"<:raw",$path);
my $data;
my $size = -s $path;
read( FH, $data, $size );
close(FH);
return $data;
}

**Comment by jeremygwa** [comment]
This sort of works, seems to be a timing issue with the server.

...
$bsky->createPost(
embed => { images => [''.rawdatafromfile(''.$mediapath)] },
lang => 'en',
text => $status.''
);

sub rawdatafromfile {
my ($path) = @_;
open(FH,"<:raw",$path);
my $data;
my $size = -s $path;
read( FH, $data, $size );
close(FH);
return $data;
}

**Comment by sanko** [comment]
Strange. Errors creating blobs in `uploadFile(...)` would be thrown in `uploadImges(...)` but you say there are no errors. And I use At protocol's old, synchronous blob creation endpoint so it should be ready to use immediately...

Well, narrowing down where things go wrong based on what's here is impossible so I'm closing this issue again.
